# Knowledge Driven Variable Selection (KDVS)
# Copyright (C) 2014 KDVS Developers. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

r"""
Provides tool scripts used for comparison of output generated by KDVS between two versions:
earlier (dubbed v1) and current (dubbed v2). KDVS v1 was published along with [Z2013]_:

.. [Z2013]  G Zycinski, A Barla, M Squillario, T Sanavia, B Di Camillo, A Verri,
           "Knowledge Driven Variable Selection (KDVS) - a new approach to enrichment analysis of gene signatures obtained from high-throughput data",
           Source Code Biol Med 8 (2013), no. 1, 2
           (http://www.scfbm.org/content/8/1/2)

All file paths are hard--coded. Unless stated otherwise, all scripts shall pass
silently; in case of an error, AssertionError is raised.
"""
